-d C:\Embedded_Dev\FPGA_Work\lab2_logic gates\impl\gwsynthesis\lab2_logic gates.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst C:\Embedded_Dev\FPGA_Work\lab2_logic gates\src\lab2_logic gates.cst
-cfg C:\Embedded_Dev\FPGA_Work\lab2_logic gates\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
