-d C:\Users\trann\OneDrive\FPGA_labs\lab14_SPI Master\impl\gwsynthesis\lab14_SPI Master Slave.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\trann\OneDrive\FPGA_labs\lab14_SPI Master\src\lab14_SPI Master Slave.cst
-cfg C:\Users\trann\OneDrive\FPGA_labs\lab14_SPI Master\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
